/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#00201e",
        "outline": "#8b9291",
        "secondary-fixed": "#ffe088",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "tertiary-fixed": "#e7e2d8",
        "outline-variant": "#414847",
        "tertiary-container": "#312f29",
        "tertiary-fixed-dim": "#cac6bd",
        "surface-tint": "#a7cec9",
        "background": "#022f2e",
        "inverse-surface": "#c1ebe6",
        "inverse-on-surface": "#0c3634",
        "on-surface": "#c1ebe6",
        "on-background": "#c1ebe6",
        "tertiary": "#cac6bd",
        "surface": "#00201e",
        "surface-bright": "#173f3c",
        "primary-container": "#0d3532",
        "surface-variant": "#123b38",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#03302d",
        "on-primary-container": "#789e9a",
        "on-tertiary-fixed": "#1d1c16",
        "error-container": "#93000a",
        "secondary": "#d6a252",
        "on-tertiary-fixed-variant": "#494740",
        "surface-container": "#002422",
        "surface-container-highest": "#123b38",
        "primary-fixed": "#c2eae5",
        "secondary-container": "#af8d11",
        "inverse-primary": "#406561",
        "on-surface-variant": "#c0c8c6",
        "surface-container-lowest": "#001110",
        "on-tertiary": "#32302a",
        "on-primary-fixed": "#00201e",
        "on-primary": "#0e3633",
        "primary": "#a7cec9",
        "on-primary-fixed-variant": "#284d4a",
        "accent-gold": "#fdf2e3",
        "accent-gold-border": "#f9e1c0",
        "sunset-teal": "#022f2e",
        "sunset-gold": "#c5a363",
        "sunset-teal-2": "#00332B",
        "sunset-gold-2": "#D4AF37",
        "sunset-gold-light": "#FDF8E7",
        "sunset-bg": "#F9FBFB",
        "sunset-teal-3": "#003831",
        "sunset-gold-3": "#b5935a",
        "sunset-beige-3": "#fdf8f1",
        "sunset-border-3": "#e5d5bc",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "unit": "8px",
        "container-margin": "24px",
        "gutter": "16px",
        "section-gap": "64px",
      },
      fontFamily: {
        serif: ['"Playfair Display"', 'serif'],
        sans: ['Inter', '"Plus Jakarta Sans"', 'sans-serif'],
        "display-lg": ['"Playfair Display"'],
        "body-md": ['"Plus Jakarta Sans"'],
        "body-lg": ['"Plus Jakarta Sans"'],
        "label-sm": ['"Plus Jakarta Sans"'],
        "headline-lg-mobile": ['"Playfair Display"'],
        "headline-lg": ['"Playfair Display"'],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["14px", { letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
